[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_MORALIS_APPLICATION_ID = "SSPePMlz2XQLX4mon3soXPHPZ2gN2NryJrWhF6rs"
  REACT_APP_MORALIS_SERVER_URL = "https://acnuawjyxtyp.usemoralis.com:2053/server"